ARG RUNNER_IMAGE="node:latest"

FROM ${RUNNER_IMAGE}

RUN apt-get update && apt-get install -y jq

COPY .taq .

WORKDIR /tezos-community

COPY ./backend .

RUN npm ci && npm run build

ENTRYPOINT ["npm", "run", "start:prod"]
