ARG RUNNER_IMAGE="node:latest"

FROM ${RUNNER_IMAGE}

RUN apt-get update && apt-get install -y jq

COPY .taq .taq

WORKDIR /tezos-community

COPY ./backend .

RUN yarn install && yarn run build

ENTRYPOINT ["npm", "run", "start:dev"]
